name: blink
description: "Blink Messaging"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  toxic: ^1.3.4
  artifact: ^1.0.14
  arcane: ^5.3.15
  rxdart: ^0.28.0
  flutter_webrtc: ^1.1.0
  crypto: ^3.0.6
  cryptography: ^2.7.0
  flutter_blue_plus: ^1.35.5
  bluetooth_low_energy: ^6.1.0
  web_socket_channel: ^3.0.3
  flutter_native_splash: ^2.4.6
  libsignal_protocol_dart: ^0.7.4
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  fast_log: ^1.0.7
  convert: ^3.1.2
  dart_libp2p_kad_dht: ^1.1.0
  dart_libp2p: ^0.5.3
  dcid: ^1.0.0
dependency_overrides:
  pointycastle: ^4.0.0
  protobuf: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  artifact_gen: ^1.0.13
  flutter_launcher_icons: ^0.14.3
flutter_native_splash:
  color: "#000000"
  color_dark: "#FFFFFF"
  branding: "assets_dev/mac_1024.png"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets_dev/icon_4096.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets_dev/blink_4096.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets_dev/mac_1024.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets_dev/mac_1024.png"
flutter:
  assets:
    - assets/
  shaders:
    - packages/arcane/resources/shaders/frost.frag
    - packages/arcane/resources/shaders/pixelate.frag
    - packages/arcane/resources/shaders/pixelate_blur.frag
    - packages/arcane/resources/shaders/rgb.frag
    - packages/arcane/resources/shaders/loader.frag
    - packages/arcane/resources/shaders/glyph.frag
    - packages/arcane/resources/shaders/invert.frag
    - packages/arcane/resources/shaders/warp.frag
    - packages/arcane/resources/shaders/black_hole.frag
    - packages/arcane/resources/shaders/lux.frag
    - packages/arcane/resources/shaders/cascade.frag
    - packages/arcane/resources/shaders/edge.frag
    - packages/arcane/resources/shaders/arcane_blur.frag
  uses-material-design: true
scripts:
  pods_macos: cd macos && rm -rf Podfile.lock && pod install --repo-update
  pods_ios: cd ios && rm -rf Podfile.lock && pod install --repo-update
  gen_models: dart run build_runner build --delete-conflicting-outputs
  gen_icons: flutter pub run flutter_launcher_icons
  gen_native_splash: dart run flutter_native_splash:create